// Generated by CoffeeScript 1.9.0
var d3, load_binary_data, moment, play_data, process, s3;

process = require('./process.js');

s3 = require('./s3.js');

d3 = require('d3');

moment = require('moment');

play_data = function(data, chart) {
  var id, index;
  index = 1;
  id = setInterval(function() {
    index += 1;
    chart(process.to_stacked_bar_data(data.slice(0, index)));
    if (index >= data.length) {
      return clearInterval(id);
    }
  }, 200);
  return id;
};

load_binary_data = function(url, callback) {
  var xhr;
  xhr = d3.xhr(url);
  xhr.responseType('arraybuffer');
  xhr.response(function(response) {
    return callback(response.response);
  });
  return xhr.get();
};

angular.module('market-playback', ['ui.bootstrap']);

angular.module('market-playback').controller('DatePicker', function($scope) {
  var curr_id, stacked_chart, url;
  $scope.today = function() {
    return $scope.dt = new Date();
  };
  $scope.today();
  $scope.clear = function() {
    return $scope.dt = null;
  };
  $scope.disabled = function(date, mode) {
    return mode === 'day' && (date.getDay() === 0 || date.getDay() === 6);
  };
  $scope.toggleMin = function() {
    var _ref;
    return $scope.minDate = (_ref = $scope.minDate) != null ? _ref : {
      "null": new Date()
    };
  };
  $scope.toggleMin();
  $scope.dateOptions = {
    formatYear: 'yy',
    startingDay: 1
  };
  $scope.formats = ['dd-MMMM-yyyy', 'yyyy/MM/dd', 'dd.MM.yyyy', 'shortDate'];
  $scope.format = $scope.formats[0];
  " Choosing symbol ";
  $scope.symbol = 'VND';
  $scope.symbols = ['PVD', 'PVC', 'PGS', 'PGC', 'PVT', 'PVS', 'PVG', 'GSP', 'PXS', 'VND', 'KLS', 'BVS', 'SSI', 'HCM', 'SHS', 'ORS', 'VDS', 'IVS', 'HPC', 'AGR', 'WSS', 'BSI', 'IDI', 'ATA', 'AVF', 'HVG', 'ANV', 'CSM', 'DRC', 'SRC', 'TNC', 'DPR', 'PHR', 'TLH', 'VGS', 'HPG', 'VIS', 'HLA', 'ITA', 'NTL', 'LCG', 'ITC', 'HQC', 'IJC', 'KBC', 'DXG', 'VCB', 'MBB', 'CTG', 'ACB', 'EIB', 'BID', 'SHB', 'BGM', 'KSS', 'KSH', 'KTB', 'KHB', 'KSD', 'DHM', 'LCM', 'BMC'];
  url = 'http://54.148.105.53:8080/pack/transactions?';
  stacked_chart = s3.StackedChart(d3.select('#chart'));
  curr_id = 0;
  return $scope.select_symbol = function(symbol) {
    var date;
    date = moment($scope.dt).format('DD/MM/YYYY');
    console.log('Symbol selected', symbol, date);
    $scope.symbol = symbol;
    return load_binary_data(url + 'symbol=' + symbol + '&date=' + encodeURIComponent(date) + '&rand=' + Math.random(), function(data) {
      clearInterval(curr_id);
      data = process.decode(data);
      data = process.un_rotate(data);
      return curr_id = play_data(data, stacked_chart);
    });
  };
});
