// Generated by CoffeeScript 1.9.0
var d3, moment, process, s3;

process = require('./process.js');

s3 = require('./s3.js');

d3 = require('d3');

moment = require('moment');

angular.module('market-playback', ['ui.bootstrap']);

angular.module('market-playback').controller('DatePicker', function($scope) {
  var alert, curr_id, load_binary_data, play_data, stacked_chart, url;
  $scope.today = function() {
    return $scope.dt = new Date();
  };
  $scope.today();
  $scope.clear = function() {
    return $scope.dt = null;
  };
  $scope.disabled = function(date, mode) {
    return mode === 'day' && (date.getDay() === 0 || date.getDay() === 6);
  };
  $scope.toggleMin = function() {
    var _ref;
    return $scope.minDate = (_ref = $scope.minDate) != null ? _ref : {
      "null": new Date()
    };
  };
  $scope.toggleMin();
  $scope.dateOptions = {
    formatYear: 'yy',
    startingDay: 1
  };
  $scope.formats = ['dd-MMMM-yyyy', 'yyyy/MM/dd', 'dd.MM.yyyy', 'shortDate'];
  $scope.format = $scope.formats[0];
  " Choosing symbol ";
  $scope.symbol = 'VND';
  $scope.symbols = ['PVD', 'PVC', 'PGS', 'PGC', 'PVT', 'PVS', 'PVG', 'GSP', 'PXS', 'VND', 'KLS', 'BVS', 'SSI', 'HCM', 'SHS', 'ORS', 'VDS', 'IVS', 'HPC', 'AGR', 'WSS', 'BSI', 'IDI', 'ATA', 'AVF', 'HVG', 'ANV', 'CSM', 'DRC', 'SRC', 'TNC', 'DPR', 'PHR', 'TLH', 'VGS', 'HPG', 'VIS', 'HLA', 'ITA', 'NTL', 'LCG', 'ITC', 'HQC', 'IJC', 'KBC', 'DXG', 'VCB', 'MBB', 'CTG', 'ACB', 'EIB', 'BID', 'SHB', 'BGM', 'KSS', 'KSH', 'KTB', 'KHB', 'KSD', 'DHM', 'LCM', 'BMC', 'VIX'];
  url = 'http://54.148.105.53:8080/pack/transactions?';
  stacked_chart = s3.StackedChart(d3.select('#chart'));
  curr_id = 0;
  $scope.alert_msg = '';
  alert = function(message) {
    return $scope.$apply(function() {
      return $scope.alert_msg = message;
    });
  };
  play_data = function(data, chart) {
    var id, index;
    index = 1;
    id = setInterval(function() {
      var date, last_time;
      index += 1;
      chart(process.to_stacked_bar_data(data.slice(0, index)));
      if (index >= data.length) {
        clearInterval(id);
        last_time = data[data.length - 1].time;
        date = moment($scope.dt).format('DD/MM/YYYY');
        return alert('Play finished, last transaction time: ' + last_time + ' in: ' + date);
      }
    }, 200);
    return id;
  };
  load_binary_data = function(url, callback, err) {
    var date, xhr;
    xhr = d3.xhr(url);
    xhr.responseType('arraybuffer');
    xhr.response(function(response) {
      return callback(response.response);
    });
    date = moment($scope.dt).format('DD/MM/YYYY');
    xhr.on('error', function() {
      return alert('There is no data for ' + $scope.symbol + ' in: ' + date);
    });
    return xhr.get();
  };
  $scope.select_symbol = function(symbol) {
    var date;
    $scope.alert_msg = 'Loading data for ' + symbol + '...';
    date = moment($scope.dt).format('DD/MM/YYYY');
    $scope.symbol = symbol;
    clearInterval(curr_id);
    return load_binary_data(url + 'symbol=' + symbol + '&date=' + encodeURIComponent(date) + '&rand=' + Math.random(), function(data) {
      alert('Chart loaded for ' + symbol + ' in: ' + date);
      data = process.decode(data);
      data = process.un_rotate(data);
      return curr_id = play_data(data.reverse(), stacked_chart);
    });
  };
  return $scope.select_symbol($scope.symbol);
});
