// Generated by CoffeeScript 1.9.0
angular.module('market-playback', ['ui.bootstrap']);

angular.module('market-playback').controller('DatePicker', function($scope) {
  $scope.today = function() {
    return $scope.dt = new Date();
  };
  $scope.today();
  $scope.clear = function() {
    return $scope.dt = null;
  };
  $scope.disabled = function(date, mode) {
    return mode === 'day' && (date.getDay() === 0 || date.getDay() === 6);
  };
  $scope.toggleMin = function() {
    var _ref;
    return $scope.minDate = (_ref = $scope.minDate) != null ? _ref : {
      "null": new Date()
    };
  };
  $scope.toggleMin();
  $scope.open = function($event) {
    $event.preventDefault();
    $event.stopPropagation();
    return $scope.opened = true;
  };
  $scope.dateOptions = {
    formatYear: 'yy',
    startingDay: 1
  };
  $scope.formats = ['dd-MMMM-yyyy', 'yyyy/MM/dd', 'dd.MM.yyyy', 'shortDate'];
  return $scope.format = $scope.formats[0];
});
